# UWSim Benchmarks Travis Continuous Integration Configuration File
sudo: required
dist: trusty
language:
  - generic
notifications:
  email:
    recipients:
      - perezsolerj@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
before_install:
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  - sudo rosdep init
  - rosdep update
install:
  # Create workspace
  - mkdir -p ~/ros/ws_uwsim/src
  - cd ~/ros/ws_uwsim/src
  - wstool init .
  - git clone -b $ROS_DISTRO-devel https://github.com/perezsolerj/underwater_simulation.git
  - git clone -b $ROS_DISTRO-devel https://github.com/perezsolerj/uwsimbenchmarks.git benchmarks
  - cd ../
  # Install dependencies for source repos
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash  
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - catkin_make -j2
